services:
  app:
    build:
      context: ./
      dockerfile: etc/go/Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=example
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./src/quickstart:/app

  db:
    image: postgres:16.2
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
